# Generated by Django 5.2.11 on 2026-02-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_userreg_password_userreg_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employerreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
                ('company_desc', models.CharField(max_length=500)),
                ('company_loc', models.CharField(max_length=500)),
                ('company_address', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('company_size', models.CharField(max_length=100)),
                ('recruiter_name', models.CharField(max_length=100)),
                ('recruiter_designation', models.CharField(max_length=100)),
                ('recruiter_email', models.EmailField(max_length=254)),
                ('recruiter_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='userreg',
            name='availability',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='bio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='degree',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='exp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='gender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='header',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='loc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='qualification',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='role',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='skills',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
