# Generated by Django 5.2.11 on 2026-02-11 07:11

from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_employerreg_alter_userreg_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerreg',
            name='Education_req',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='employerreg',
            name='Exp_level',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='employerreg',
            name='app_deadline',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='employerreg',
            name='job_desc',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='employerreg',
            name='job_title',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='employerreg',
            name='job_type',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='employerreg',
            name='joining_time',
            field=models.DateField(default=date.today),
        ),
        migrations.AddField(
            model_name='employerreg',
            name='req_skills',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='employerreg',
            name='salary_range',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='employerreg',
            name='salary_type',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='employerreg',
            name='vacancies',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='employerreg',
            name='work_mode',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
    ]
