# Generated by Django 5.2.11 on 2026-02-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_employerreg_education_req_employerreg_exp_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerreg',
            name='joining_time',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
    ]
