# Generated by Django 5.2.11 on 2026-02-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_employerreg_joining_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerreg',
            name='app_deadline',
            field=models.DateField(default='2026-01-01'),
        ),
    ]
