# Generated by Django 5.2.11 on 2026-02-11 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_employerreg_app_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerreg',
            name='app_deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
