# Generated by Django 5.2.11 on 2026-02-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_employerreg_app_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobapplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicantname', models.CharField(max_length=255)),
                ('applicantnumber', models.IntegerField(max_length=10)),
                ('applicantemail', models.EmailField(max_length=254)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
