# Generated by Django 5.2.11 on 2026-02-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerreg',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Remote', 'Remote')], max_length=50),
        ),
    ]
