# Generated by Django 5.2.11 on 2026-02-20 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_message_conversation_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='home.employerreg'),
            preserve_default=False,
        ),
    ]
