# Generated by Django 5.2.11 on 2026-02-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_jobapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='skills',
            field=models.TextField(max_length=255),
        ),
    ]
