# Generated by Django 5.2.11 on 2026-02-24 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_userreg_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='username',
        ),
        migrations.AddField(
            model_name='userreg',
            name='user',
            field=models.OneToOneField(default=8, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userreg',
            name='availability',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='degree',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='exp',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='gender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='header',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='loc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
